Repository xyvora/achievaim, pull requests merged in 2023-07, with the labels that each got.

#47 Fix CI passing when it shouldn't
  .github/workflows/testing.yml
  justfile
Labels: skip-changelog

#44 Add user management
  backend/app/api/deps.py
  backend/app/api/v1/api.py
  backend/app/api/v1/routes/goal.py
  backend/app/api/v1/routes/health.py
  backend/app/api/v1/routes/user.py
  backend/app/config.py
  backend/app/core/__init__.py
  backend/app/core/config.py
  backend/app/core/security.py
  backend/app/core/utils.py
  backend/app/db.py
  backend/app/main.py
  backend/app/models/goals.py
  backend/app/models/object_id.py
  backend/app/models/user.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/conftest.py
  backend/tests/test_goal_routes.py
  backend/tests/test_health_routes.py
  backend/tests/test_security.py
  backend/tests/test_user_model.py
  backend/tests/test_user_routes.py
  docker-compose.yml
Labels: enhancement

#48 Fix frontend lint and test errors
  .github/workflows/testing.yml
  frontend/src/lib/components/Navbar.svelte
  frontend/src/routes/account/+page.svelte
  frontend/src/routes/home/+page.svelte
  frontend/src/routes/smartgoals/+page.svelte
  frontend/tests/create_index.spec.ts
  frontend/tests/smartgoals.spec.ts
Labels: skip-changelog

#49 Disable pre-commit mypy
  .pre-commit-config.yaml
Labels: skip-changelog

#60 Update dependabot settings
  .github/dependabot.yml
Labels: skip-changelog

#61 Fix dependabot error
  .github/dependabot.yml
Labels: skip-changelog

#71 Bump pre-commit dependencies
  .pre-commit-config.yaml
Labels: skip-changelog, dependencies

#72 Fix playwright install in CI
  .github/workflows/testing.yml
  justfile
Labels: skip-changelog

#87 Update readme
  README.md
Labels: skip-changelog

#70 Add validators to account fields
  frontend/src/routes/account/+page.svelte
  frontend/tests/account.spec.ts
Labels: enhancement

#100 Bump pre-commit hooks
  .pre-commit-config.yaml
Labels: skip-changelog, dependencies

#101 Remove redundant backend checks
  .github/workflows/testing.yml
Labels: skip-changelog

#108 Override rounds for testing
  backend/app/core/security.py
  backend/tests/conftest.py
Labels: skip-changelog

#110 Remove extra files
  package-lock.json
  package.json
Labels: skip-changelog

#111 Set navbar active class for home
  frontend/src/lib/components/Navbar.svelte
Labels: bug

#115 Add logo to README.md
  README.md
Labels: skip-changelog

#122 Add testing badges to README
  README.md
Labels: skip-changelog

#123 Fix typos
  README.md
Labels: skip-changelog

#129 Add no-commit-to-branch to pre-commit
  .pre-commit-config.yaml
Labels: skip-changelog

#140 Add funding config
  .github/FUNDING.yml
Labels: skip-changelog

#173 Fix flashing screen on logout
  frontend/src/lib/components/AccountInfoForm.svelte
Labels: bug

#174 Add account info tests
  frontend/src/lib/components/AccountInfoForm.svelte
  frontend/tests/account_settings.spec.ts
Labels: skip-changelog

#183 Remove unused import
  frontend/src/lib/components/AccountInfoForm.svelte
Labels: skip-changelog

#184 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: skip-changelog

#185 Bump frontend dependencies
  frontend/package-lock.json
Labels: skip-changelog, dependencies

#189 Revert end to end testing
  .github/workflows/testing.yml
  frontend/tests/end_to_end.spec.ts
Labels: skip-changelog

#172 Fix extra menu items showing on load
  frontend/package.json
  frontend/src/lib/components/AccountInfoForm.svelte
  frontend/src/lib/stores/stores.ts
  frontend/src/routes/+page.svelte
Labels: bug

#192 Fix backend docker prod
  backend/Dockerfile
  backend/poetry.lock
  backend/pyproject.toml
Labels: skip-changelog

#195 Make country optional
  backend/app/models/user.py
  backend/app/services/user_service.py
Labels: bug

#196 Add logging code
  frontend/src/lib/components/AccountInfoForm.svelte
Labels: skip-changelog

#200 Convert user name before login
  backend/app/services/user_service.py
Labels: bug

#201 Remove country check
  frontend/src/lib/components/AccountInfoForm.svelte
Labels: bug

#203 Fix handling of country when missing
  backend/app/models/user.py
  backend/app/services/user_service.py
Labels: bug

#215 Update backend/tests/test_login_routes.py
  backend/tests/test_login_routes.py
Labels: skip-changelog

#230 Add no-unused-vars to errors
  frontend/.eslintrc.cjs
Labels: skip-changelog

#231 Fix typo
  README.md
Labels: skip-changelog
