Repository xyvora/achievaim, pull requests merged in 2023-08, with the labels that each got.

#271 Remove camel-converter
  backend/poetry.lock
  backend/pyproject.toml
Labels: skip-changelog

#272 Bump beanie from 1.20.0 to 1.21.0
  backend/poetry.lock
  backend/pyproject.toml
Labels: skip-changelog, dependencies

#273 Bump fastapi 0.99.1 > 0.101.0 pydantic 1.10.12 > 2.1.1
  backend/app/core/config.py
  backend/app/models/object_id.py
  backend/app/models/user.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/test_object_id.py
  backend/tests/test_user_model.py
Labels: skip-changelog

#278 Add create user end to end test
  .github/workflows/testing.yml
  docker-compose-testing.yml
  frontend/playwright.config.ts
  frontend/src/lib/components/AccountInfoForm.svelte
  frontend/tests/index.spec.ts
  justfile
Labels: skip-changelog

#279 Add login test
  .github/workflows/testing.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
  frontend/tests/end_to_end.spec.ts
  frontend/tests/index.spec.ts
Labels: skip-changelog

#281 Add invalid login and user update tests
  frontend/tests/end_to_end.spec.ts
Labels: skip-changelog

#288 Bump ruff and prettier pre-commit hooks
  .pre-commit-config.yaml
Labels: skip-changelog, dependencies

#289 Add cache for node packages in CI
  .github/workflows/testing.yml
Labels: skip-changelog

#290 Increate expect timeout
  frontend/playwright.config.ts
Labels: skip-changelog

#291 Set tracing on
  frontend/playwright.config.ts
  frontend/src/lib/axios-config.ts
Labels: skip-changelog

#292 Change trailingComma to all in prettier
  frontend/.eslintrc.cjs
  frontend/.prettierrc
  frontend/playwright.config.ts
  frontend/postcss.config.cjs
  frontend/src/lib/api.ts
  frontend/src/lib/components/AccountInfoForm.svelte
  frontend/src/lib/components/EditGoal.svelte
  frontend/src/lib/components/EditGoalComponent.svelte
  frontend/src/routes/+page.svelte
  frontend/src/routes/create-goals/+page.svelte
  frontend/src/routes/edit-goal/+page.svelte
  frontend/src/routes/testing/+page.svelte
  frontend/src/routes/testingcomponents/+page.svelte
  frontend/svelte.config.js
  frontend/tailwind.config.cjs
  frontend/tests/end_to_end.spec.ts
  frontend/vite.config.ts
Labels: skip-changelog

#299 Use prod build for tests
  .github/workflows/testing.yml
Labels: skip-changelog

#300 Fix tailwind warning
  frontend/tailwind.config.cjs
Labels: skip-changelog

#311 Fix card expanding
  frontend/src/lib/components/GoalCard.svelte
  frontend/tests/index.spec.ts
Labels: bug

#317 Bump pre-commit dependencies
  .pre-commit-config.yaml
Labels: skip-changelog, dependencies

#332 Fix bug where goals didn't show at login
  frontend/src/routes/+page.svelte
Labels: bug

#336 Update README.md
  README.md
Labels: skip-changelog

#340 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: skip-changelog, dependencies
